export const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality proudcts',            
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: "Shirts",
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Addidas',
            rating: 4.0,
            numReviews:10,
            description:'high quality proudcts',            
        },
        {
            _id: '3',
            name: 'Lascoste Free Shirt',
            category: "Shirts",
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description:'high quality proudcts',            
        },
        {
            _id: '4',
            name: 'Nike Slim Pant',
            category: "Pants",
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description:'high quality proudcts',            
        },
        {
            _id: '5',
            name: 'Puma Slim Pant',
            category: "Pant",
            image: '/images/p5.jpg',
            price: 6,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.3,
            numReviews: 10,
            description:'high quality proudcts',            
        },
        {
            _id: '6',
            name: 'Adidas Fit Pant',
            category: "Pants",
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 15,
            description:'high quality proudcts',            
        },
        {
            _id: '7',
            name: 'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality proudcts',            
        },
        {
            _id: '8',
            name: 'Adidas Fit Shirt',
            category: "Shirts",
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Addidas',
            rating: 4.0,
            numReviews:10,
            description:'high quality proudcts',            
        },
        {
            _id: '9',
            name: 'Lascoste Free Shirt',
            category: "Shirts",
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description:'high quality proudcts',            
        },
        {
            _id: '10',
            name: 'Nike Slim Pant',
            category: "Pants",
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description:'high quality proudcts',            
        },
        {
            _id: '11',
            name: 'Puma Slim Pant',
            category: "Pant",
            image: '/images/p5.jpg',
            price: 6,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.3,
            numReviews: 10,
            description:'high quality proudcts',            
        },
        {
            _id: '12',
            name: 'Adidas Fit Pant',
            category: "Pants",
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 15,
            description:'high quality proudcts',            
        },
        {
            _id: '13',
            name: 'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality proudcts',            
        },
        {
            _id: '14',
            name: 'Adidas Fit Shirt',
            category: "Shirts",
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Addidas',
            rating: 4.0,
            numReviews:10,
            description:'high quality proudcts',            
        },
        {
            _id: '15',
            name: 'Lascoste Free Shirt',
            category: "Shirts",
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description:'high quality proudcts',            
        },
        {
            _id: '16',
            name: 'Nike Slim Pant',
            category: "Pants",
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description:'high quality proudcts',            
        },
        {
            _id: '17',
            name: 'Puma Slim Pant',
            category: "Pant",
            image: '/images/p5.jpg',
            price: 6,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.3,
            numReviews: 10,
            description:'high quality proudcts',            
        },
        {
            _id: '18',
            name: 'Adidas Fit Pant',
            category: "Pants",
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 15,
            description:'high quality proudcts',            
        },
        {
            _id: '19',
            name: 'Nike Slim Shirt',
            category: "Shirts",
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality proudcts',            
        },
        {
            _id: '20',
            name: 'Adidas Fit Shirt',
            category: "Shirts",
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Addidas',
            rating: 4.0,
            numReviews:10,
            description:'high quality proudcts',            
        },
        {
            _id: '21',
            name: 'Lascoste Free Shirt',
            category: "Shirts",
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description:'high quality proudcts',            
        },
        {
            _id: '22',
            name: 'Nike Slim Pant',
            category: "Pants",
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description:'high quality proudcts',            
        },
        {
            _id: '23',
            name: 'Puma Slim Pant',
            category: "Pant",
            image: '/images/p5.jpg',
            price: 6,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.3,
            numReviews: 10,
            description:'high quality proudcts',            
        },
        {
            _id: '24',
            name: 'Adidas Fit Pant',
            category: "Pants",
            image: '/images/p6.jpg',
            price: 139,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 15,
            description:'high quality proudcts',            
        },
    ]
}